### ISSUE TITLE
rgba definition in _link.scss

### ISSUE THREAD

**Issue by tuxenberger** [ErdmannFreunde/euf_nutshell#5]
Hallo Dennis,

bei den buttons wird der hover bei mir farblich nicht berechnet:

files/nutshell/scss/components/_links.scss
Zeile: 16

--button-bg-hover:       rgba(var(--button-bg) * 0.8);

Bei SCSS vars ging das, bei den html var scheinbar nicht mehr - ich bekomme im FF keine Hintergundfarbe für den :hover angezeigt.

Grüße, Marcel

**Comment by denniserdmann** [comment]
Stimmt. Ich werde einen Fix in den nächsten Tagen veröffentlichen, gesammelt mit weiteren Bugs, die noch im Framework sind.
